### ISSUE TITLE
Swagger UI overrides accept header parameter

### ISSUE THREAD

**Issue by rautenberg** [opentox/lazar-rest#1] opened 2017-02-24 11:54 UTC
see also : https://github.com/swagger-api/swagger-ui/issues/1448
accept parameter will be overwritten by swagger UI 
```
 parameters:
        - name: accept
          in: header
          description: requested Content-Type
          required: true
          type: string
          enum:
            - text/uri-list
            - application/json
        - $ref: '#/parameters/subjectid'
      produces:
        - text/uri-list
        - application/json
      responses:
        '200':
          $ref: '#/responses/200'

```
gives `curl -X GET --header 'Accept: text/uri-list' --header 'accept: application/json' 'https://enm.in-silico.ch/bla`

exchange it with this notation operates OK:
```
 parameters:
        - $ref: '#/parameters/subjectid'
      produces:
        - text/uri-list
        - application/json
      responses:
        "200":
          schema:
            type: string
          description: bla
```

`curl -X GET --header 'Accept: text/uri-list' 'https://enm.in-silico.ch/bla'`

**Comment by gebele** [comment] 2017-07-07 11:21
It's not a bug in lazar-rest lib and we have a workaround for it hence I close it.

**Closed by gebele** 2017-07-07 11:21 UTC

**Comment by prativapokhrel** [comment] 2017-08-09 17:17
I had the same issue and I tried to hardcode the swagger.js file which actually worked. I changed "responseContentType = application/json" to "responseContentType = value of accepts parameter". Hope it works for you as well :)
